### ISSUE TITLE
[BUG] Replace User

### ISSUE THREAD

**Issue by kdanzer-tgm** [Local-Admin-BurgerKing/core#17]
## Replace Method (User)
There is a wrong SQL requestion. The name of the method is `replaceUser` and is located in the class `UserManager`

## Reproduce
1. Go to `UserApiTest` in the `java-client`
2. Start it with JUnit (Care that there is not @Ignore infront of the replace test)
3. Look at the Error
4. See that there is an error when getting user by the new email
5. Recognize that email has not been changed

## Expected
When the user gets replaced it should replace following values:
- Name
- Mail
- Group

It should not replace these values:
- password

## Actual
![image](https://user-images.githubusercontent.com/44087538/70916002-32666a80-201b-11ea-83da-eb0b03da671f.png)
All values are correct but E-Mail should not be `sexysusi@gmx.at` but `Herbert1973@gmail.com`.

## Additional
The reason why there is a Replace method is, that the user is able to change his Mail-Address. Removeing the user and add it again can cause problems and is not that nice because it is morecomplicated to use.

**Comment by nbrugger-tgm** [comment]
## Lack of infromation
Is replace user meant to also allow to replace the identifier(email).
This makes no sense to me as the operation would be equal to deleting an user completely and define a complete new one.
