### ISSUE TITLE
[BUG] Delete All Users

### ISSUE THREAD

**Issue by kdanzer-tgm** [Local-Admin-BurgerKing/core#18]
## Delete all users is useless as it is right now
The method `deleteAllUsers` is useless at the moment. One is not allowed to remove users with the Root permission and so it is not possible to use this Method. (Which is good otherwise one could not add anything ever again). 

## Reproduce
1. Login with API-Key
2. Create a UserApi
3. Use `userApi.deleteAllUsers`

## Better
`deleteAllUsers` should delete all users which have no Root permission.

**Comment by nbrugger-tgm** [comment]
## Done
`deleteAllUsers` now only deletes non `ROOT` users. This should fix the issue
