### ISSUE TITLE
[BUG] Delete all Column

### ISSUE THREAD

**Issue by kdanzer-tgm** [Local-Admin-BurgerKing/core#19]
## Error when deleting columns
When I delete all `DailyColumns` or `DailyFormulas` I get this error:
``{"message":"org.jooq.exception.DataAccessException: SQL [insert into `local_admin`.`column` (`name`, `description`, `order`) values (?, ?, ?)]; Duplicate entry 'dailycolumn' for key 'PRIMARY'","code":1}``

Further more I can delete dailyColumns and DailyFormulas by hand in MySQL but not Column as one can see here;
![image](https://user-images.githubusercontent.com/44087538/70849193-5f7c1700-1e7b-11ea-8adb-5ed7d2b893a6.png)
I get this error:
``ERROR 1451 (23000): Cannot delete or update a parent row: a foreign key constraint fails (`local_admin`.`daily_column`, CONSTRAINT `daily_column_is_column` FOREIGN KEY (`name`) REFERENCES `column` (`name`) ON DELETE RESTRICT ON UPDATE RESTRICT)`
when I use this command: `DELETE from local_admin.column;``

## Reproduce
1. Go to `ColumnApiTest` in java-client
2. Set `resetColumnTableBefore` to `true`
3. Execute `ColumnApiTest`

## Expected
There should be no error and when all columns get deleted!

**Comment by nbrugger-tgm** [comment]
## Wrong
The fail happened in the rest API not in the core.
### Rejected & Closed

**Comment by kdanzer-tgm** [comment]
## Open
Is not closed because the error seems not to be in the api. It seems more like the error is in the Database. 
Errors in rest-api got fixed but even when `deleteAll` throws no error it still does not delete it in the `column`-Table

**Comment by nbrugger-tgm** [comment]
## Missing information
Please post a short 'in core' code (only using Managers), which shows up the unwanted behavior

**Comment by nbrugger-tgm** [comment]
## Test Code Sample
```java
Database.init("localhost:100", "root", null);
        DailyColumnManager.addDailyColumn(new DailyColumn("aaa", (byte)1),"");
        DailyColumnManager.addDailyColumn(new DailyColumn("bbb", (byte)1),"");
        DailyColumnManager.addDailyColumn(new DailyColumn("ccc", (byte)0),"");

        FormulaManager.addDailyformula(new Formula("fff", "ADD", "aaa","bbb",(byte)0), "");

        FormulaManager.deleteAllDailyformulas();
        DailyColumnManager.deleteAllDailycolumns();
```
This code does works.
