### ISSUE TITLE
[BUG] Edit User Password

### ISSUE THREAD

**Issue by kdanzer-tgm** [Local-Admin-BurgerKing/core#20]
## Password does not get changed when edit
It seems like the password gets randomized when it gets edited. So it does not get changed to the delivered password, but is not the same after each execute

## Reproduce
1. Execute `UserApiTest`
2. Look at the password in the db of the user `kalia*.*****@gmail.com`
3. Execute again
4. Password of the user is not the same as before

## Expected Behaviour
Password should get changed after first edited but not after 2nd

## Current Behaviour
Password gets randomized after the 2nd edit and is not even close the same hash each time.

(For a more clear info wirte to me, was not that easy to explain that behaviou because its pretty weird)

**Edit**
When the deliverd Password is null and `AccountManager.authenvicate` does not get executed it works. Error must be in `AccountManager.authenvicate`.

**Comment by nbrugger-tgm** [comment]
## Additional information
#### Authentication Behavior
When you try to authenticate as a user with a wrong password the user will be unable to login (reponse: auth failed) for the next 2 seconds.
#### Password Changing
When setting a new password, the password should be auto generated and sent via email. So this will need hand made testing
#### Hash & Cryptographic
> We do not use hash

We use a special type of Obfuscation and encryption. Here is the pseudo code:
```
var pwd = /*Whatever you like*/;
user.storePassword(pwdByteCode: encryptAES(content: pwd,key: makeKeyFrom(keyOrigin: pwd)))
```
Note:
> `encryptAES` has some Randomnes going on so encryptAES("test","somekey") returns a different value each time called, so you cant read anything from the '''hash'''

**Comment by kdanzer-tgm** [comment]
## Question
It makes no sense that the user password gets randomized when it edit something but setting a wrong password. 

### What should happen
When I edit the user and give a wrong password I am still allowed to edit the name for example (As long as I am logged in). 
When I deliver the correct password it should also be able to edit the password. 
Randomizing the password when I auth with a wrong would cause many problems.

**Comment by nbrugger-tgm** [comment]
## Invalid
for me the code works
```java
Database.init("localhost:100", "root", null);
User u = new User();
u.setEmail("test@gmail.com");
u.setPermissionGroup("ROOT");
u.setUsername("Test");
String pwd = "ichBin1KühlesPasswörter";
AccountManager.addUser(u,pwd);
System.out.println("Auth first : "+AccountManager.authenticate(u.getEmail(), pwd));
System.out.println("Change pwd");
pwd = "einNeuesPasswörtermir123";
AccountManager.setPassword(u.getEmail(),pwd);
System.out.println("Auth sec : "+AccountManager.authenticate(u.getEmail(), pwd));
```

**Comment by kdanzer-tgm** [comment]
## Wrong Test
Your example seems not to be correct. You are setting the password instantly at the `AccountManager`. 
### Problem
The problem is, when the user gets edited with the method 
`editUser(String mail, String oldPassword, AutoGenUserOptional user)` (which is located in the `UserApiController` class)
it sets the password of the user to a new random password when the deliverd password is not correct.

### Example
'''
UserApi api = new UserApi();
User user1 = new User();
user1.setEmail("AnEmail@gmail.com");
user1.setName("A name");
user1.setPassword("IAmAPassword1234!?");
user1.setGroup("ROOT");

api.addUser(user1);

Useroptional edits1 = new Useroptional();
edits1.setName("Herbert Pratzel");
edits1.setEmail("hpratzel@student.tgm.ac.at");
edits1.setPassword("Aldar&/67");

//This works fine
api.editUser(user1.getEmail(), edits1, user1.getPassword());
usersApi.authenticate(user1.getEmail(), edits1.getPassword()); // Should work like that

//Get back to admin user
usersApi.authenticate("admin@kingrestaurants.at", "12345678");


Useroptional edits2 = new Useroptional();
edits2.setPassword("PasswordWhichShouldNotGetSet!");

//Does not throw an error all good
api.editUser(user1.getEmail(), edits2, "AWrongPW.PWShouldStillBeFromEdit1LikeThat");
//This does not work even though it should
usersApi.authenticate(user1.getEmail(), edits1.getPassword());

//Get back to admin user
usersApi.authenticate("admin@kingrestaurants.at", "12345678");
```

**Comment by nbrugger-tgm** [comment]
This seems to be a bug in rest-api. The core feature of changing a password does exactly what ist meant to to
