### ISSUE TITLE
[BUG] Rename filter - creates new filter

### ISSUE THREAD

**Issue by Tbswss** [Local-Admin-BurgerKing/core#21]
**Describe the bug**
If a existing filter gets renamed, via the com.finance.manager.FilterManager.renameFilter method, the existing filter is NOT renamed, instead a new filter, with the new name (the name the original filter should now have), is created. 
Consequently the filter_column table and it's entries are also not updated, and reference the original filter.

**To Reproduce**
Create any existing filter via the FilterManager and rename it via the above mentioned method.
In my example, I executed the "FiltersApiTest" inside the "java-client" repository, but it's useful to remove all @Test annotations from other tests, except "renameFilterTest", to see the actual mistake inside the db table.

**Expected behavior vs actual**
Expected:
If you look at the screenshot provided below, you will see there are 2 filters: "Filter1" and "Filter45". Furthermore the 2 entries in the "filter_column" table reference Filter "Filter1". 
"Filter1" should not exists, only 1 entry ("Filter45") should be in the table AND the entries in the "filter_column" table should reference "Filter45".

Actual result:
![screenshot](https://user-images.githubusercontent.com/21243428/70865393-63806580-1f5d-11ea-878e-3c97c408ceb5.jpg)

**Additional context**
The problem is the last statement in the FilterManage.renameFilter Method: "rec.store()". As stated in the documentation of the method: "If this record was loaded by jOOQ and the primary key value was changed, an INSERT statement is executed (unless Settings.isUpdatablePrimaryKeys() is set). jOOQ expects that primary key values will never change due to the principle of normalisation in RDBMS. So if client code changes primary key values, this is interpreted by jOOQ as client code wanting to duplicate this record.".
I tried changing the "rec.store" to "rec.update", but the result was, that nothing was changing.

**Comment by nbrugger-tgm** [comment]
## Nice Work
You did a nice work regarding to your research effort. I will take a look at this problem soon

**Comment by nbrugger-tgm** [comment]
## Done
