### ISSUE TITLE
[BUG] Add Daily Report - Date is shifted 1 day back.

### ISSUE THREAD

**Issue by Tbswss** [Local-Admin-BurgerKing/core#22]
**Describe the bug**
If you add a daily report via the "addDailyReport" Endpoint method (yes, ENDPOINT, but read on) the date is shifted by 1 day to the past. E.g:
+ Date provided to the endpoint: 2019-12-15
+ Date in the database: 2019-12-14
I checked the console output of the rest-api, and the correct query seems to be executed, with the correct date, therefore it cant be an endpoint issue.

**To Reproduce**
Add a daily report via the ReportManager.
In my case, I executed the "TablesApiTest" in the "java-client" repository. You can run the test yourself, but i would comment put any "@Test" except above the "dailyReportAddGetEditRemoveTest" Method.

**Expected behavior vs actual**
Excpected:
The report in the "daily_report" db table should have a "date"-value of "2019-12-15".

Actual:
![screenshot_002](https://user-images.githubusercontent.com/21243428/70866216-4ea8cf80-1f67-11ea-91ac-78e4ff863dd0.jpg)

**Additional context**
Received result on the rest-api endpoint:
![screenshot_001](https://user-images.githubusercontent.com/21243428/70866240-90397a80-1f67-11ea-8196-9fceaa64f03a.jpg)

Executed query:
![screenshot_000](https://user-images.githubusercontent.com/21243428/70866239-8e6fb700-1f67-11ea-923c-b5fc5d5c8efd.jpg)

As this problem is not new to @nbrugger-tgm i didnt focus on searching the exact source of the problem, as i think @nbrugger-tgm already knows the fix to this problem. If not I can provide further documentation.

**Comment by nbrugger-tgm** [comment]
## Invalid
This **might** not be a problem of the core as if you execute the code directly in the core everything works fine.
## General Information
It is always important that the Database and the Application are using the same TZ
## Solution
At the moment i don't have a clean solution

**Comment by nbrugger-tgm** [comment]
#9

**Comment by nbrugger-tgm** [comment]
## Fixed
