### ISSUE TITLE
[BUG] Replace DailyColumn

### ISSUE THREAD

**Issue by kdanzer-tgm** [Local-Admin-BurgerKing/core#27]
**Describe the bug**
When the DailyColumn gets replaced it does not replace the name but all other values.

**To Reproduce**
1. Go to `DailycolumnApiTest` located in java-client
2. Go to the `dailycolumnReplaceTest()` method
3. Execute it
4. See error which is cause because the name did not change

**Expected behavior**
When the dailycolumn gets replaced the name of it should change in the column and in the daily_column table as well es everywhere where is is referenced.

**Actual behavior**
Name does not change anywhere

**Comment by nbrugger-tgm** [comment]
# Fixed

**Comment by kdanzer-tgm** [comment]
## Not Fixed?
The issue seems to still occur.
