### ISSUE TITLE
[BUG] Random 404 on existing report when removing

### ISSUE THREAD

**Issue by Tbswss** [Local-Admin-BurgerKing/core#28]
**Describe the bug**
My scenario: I added two daily reports, one with the date **2019-12-17** (restaurant 0) and **2019-11-15** (restaurant 1). While accessing both of these daily reports ("accessing" in getting the reports values e.g.) I had no problems.
But when I tried to remove both of them, one would not be found and a 404 response is returned. It's the report from **2019-11-15**. But after checking it doesnt depend on the date, i tried changing it, nothing changed. Furtermore it doesnt depend on the restaurant they are in, I changed of both them, nothing changed.

**To Reproduce**
Create two daily reports, one with the current date (LocalDate.now()) and one with the **2019-11-15**. The first doesnt have any data-entries, the second has the value "-4" for the column "c1". (I dont know if this is important).
Then add both of these, it should not matter in which restaurant. (via addDailyReport()).
Afterwards try removing them again, with "removeReport".

**Expected behavior vs actual**
Expected:
Both reports are removed from the database.

Actual:
One report is removed, the other one is 404 not found.

**Additional context**
While writing this, I randomly tried changing the second date (2019-11-15) to a later date than the first one (2019-12-17, todays date). I changed it to **2019-12-30**. That worked removing. So it has to depend on the date somehow I think. They "funny" thing is.... I changed it from **2019-12-30** to **2019-12-15**, which didnt workt again.....

I looked in the console and I noticed following:
This image shows the request (DELETE) to remove the report from **2019-11-15**. But after receiving the request, the api "instantly" returns 404. BUT
![deleting_filter2](https://user-images.githubusercontent.com/21243428/71040050-f966ec80-2125-11ea-8686-45653b27fc48.jpg)
If you look at these 2 pictures. This is the request to remove **2019-12-17**. First, after the request the authentication process is started, which is missing by above report, but that could be a session thing so it doesnt really matter.
BUT, in the second picture you see the sql statements being executed.
![filter1_removing](https://user-images.githubusercontent.com/21243428/71040116-22877d00-2126-11ea-93a1-938f8832c7ff.jpg)
![filter1_removal2](https://user-images.githubusercontent.com/21243428/71040118-24514080-2126-11ea-82dc-2b0518eeb264.jpg)

Maybe, the ORM caches the database and is not synced, but I have no clue about this, but that wouldn't explain the "random" like finding.

**Comment by Tbswss** [comment]
Btw, I cut out the authentication process at the last picture, because it's unnecessary.

**Comment by Tbswss** [comment]
And fyi, the executing test was "TablesApiTest.reportsGetAllGetAtDateTest. (all filter related subtests in this method are commented out, because they are no testable, because of the get requestbody client-issue)

**Comment by Tbswss** [comment]
It has, how it appears to me, definitely something to do with the reports being in the past. (Aka before todays date), and I have absolutely no clue why.

**Comment by Tbswss** [comment]
The same errror happens when updating a column value of a report. Same error, 2019-11-15 is not working, everything above 2019-12-17 is working.

**Comment by nbrugger-tgm** [comment]
## Reporoduction
I cannot reproduce the error. Here is the code i used. It works:
```java
Database.init("localhost:100", "root", null);

if(!RestaurantManager.contains(111))
    RestaurantManager.addRestaurant(new Restaurant(111, "TestTest", "gg", (byte) 1, 20.0));

if(!DailyColumnManager.contains("haXhaX"))
    DailyColumnManager.addDailyColumn(new DailyColumn("haXhaX", (byte) 0), "");

System.out.println("------[Report1]-------");
DailyReport report1 = new DailyReport(Date.valueOf("2019-11-15"), 111, "");
DailyReport report2 = new DailyReport(Date.valueOf(LocalDate.now()), 111, "");
if(ReportManager.contains(report1.getDate(), 111)) {
    System.out.println("Report 1 ("+report1.getDate()+") is already there, delete");
    ReportManager.removeReport(report1.getDate(), 111);
}
ReportManager.recordReport(report1);
ReportManager.removeReport(report1.getDate(), 111);

System.out.println("------[Report2]-------");
if(ReportManager.contains(report2.getDate(), 111)) {
    System.out.println("Report 2 (" + report1.getDate() + ") is already there, delete");
    ReportManager.removeReport(report2.getDate(), 111);
}
ReportManager.recordReport(report2);
ReportManager.setValue(report2.getDate(), 111, "haXhaX", 12120);
ReportManager.removeReport(report2.getDate(), 111);

System.out.println("----[Clean Up]-----");

DailyColumnManager.deleteDailycolumn("haXhaX");
RestaurantManager.deleteRestaurant(111);
```

**Comment by nbrugger-tgm** [comment]
@tweiss-tgm please review

**Comment by nbrugger-tgm** [comment]
## Not Reproduceable
Open it again if you found a way to reproduce
